### ISSUE TITLE
Ingest rate limiting is not precise

### ISSUE THREAD

**Issue by vlastahajek** [bonitoo-io/influxdb-comparisons#2]
I set limiting to 1M val/s, but final result was only 900k vals/s. 10% error is too much

`/home/ubuntu/go/bin/bulk_data_gen --use-case=dashboard --seed=123 --format=influx-bulk --scale-var=100 --timestamp-start=2018-01-03T00:00:01Z
--timestamp-end=2018-01-10T00:00:00Z | /home/ubuntu/go/bin/bulk_load_influx --urls=http://ip-10-2-1-54.us-west-1.compute.internal:8086,http://ip-10-2-1-224.us-west-1
.compute.internal:8086,http://ip-10-2-1-237.us-west-1.compute.internal:8086,http://ip-10-2-1-234.us-west-1.compute.internal:8086 --batch-size=5000 --do-load=true --w
orkers=16 --report-host=https://10.0.115.65:8086 --report-tags=database_build:ENT,database_data_nodes:4,database_index:inmem,database_meta_nodes:3,database_name:Infl
uxDB,database_node_type:data,database_version:1.6.2-c1.6.2,hosts:100,hours:24,instance_type:r4.2xlarge,query_type:dashboard-all,use_case:dashboard --report-user=repo
rter --report-password=benchmarks2017 --db=benchmark_db --consistency=one --replication-factor=1 --ingest-rate-limit=1000000 --do-abort-on-exist=false`

using random seed 123
daemon URLs: [http://ip-10-2-1-54.us-west-1.compute.internal:8086 http://ip-10-2-1-224.us-west-1.compute.internal:8086 http://ip-10-2-1-237.us-west-1.compute.internal:8086 http://ip-10-2-1-234.us-west-1.compute.internal:8086]
results report destination: https://10.0.115.65:8086
results report database: database_benchmarks
hostname for results report: ip-10-2-1-45
results report tags: [[database_build ENT] [database_data_nodes 4] [database_index inmem] [database_meta_nodes 3] [database_name InfluxDB] [database_node_type data] [database_version 1.6.2-c1.6.2] [hosts 100] [hours 24] [instance_type r4.2xlarge] [query_type dashboard-all] [use_case dashboard]]
2018/09/19 14:57:24 Info: there are databases already in the data store.
2018/09/19 14:57:24 Using worker ingestion rate 62500 values/1000 ms
2018/09/19 14:57:24 Calculated batch size hint: 324 (allowed min: 500 max: 5000)
2018/09/19 14:57:24 Adjusting batchSize from 5000 to 500
2018/09/19 15:09:13 Written 66526900 points, 641077400 values, took 708.835012 seconds
...
loaded 66526900 items in 709.451695sec with 16 workers (mean point rate 93772.275823/sec, **mean value rate 903623.748840/s**, 37.67MB/sec from stdin)

**Comment by vlastahajek** [comment]
Test  was done during parallel querying of server. Maximum ingest rate was 2.9M val/s, ingest rate while querying (without limiting) was 2.2M vals/s

**Comment by alespour** [comment]
Fix committed and pull request created.
